### ISSUE TITLE
Three methods of starting the blockchain download

### ISSUE THREAD

**Issue by chjj** [bitpay/bitcoind.js#1]
Hey guys,

Right now, bitcoindjs.cc has 3-4 different methods of starting the blockchain download (as if you were to run bitcoind straight away). Most of them have problems (the first which simply starts the boost threads in net.cpp cannot connect to peers). The AppInit2 methods start downloading the blockchain but have exception issues. The AppInit method gets run on the node thread pool. It works well, but the callback never gets executed because AppInit blocks, adding -daemon to the argv isn't what we want because it will just fork it.

Would love people to mess around with this and bitpay/libbitcoind. Checkout src/bitcoindjs.cc

**Comment by kleetus** [comment]
I've been messing around with these bindings. Quite a lot of work went into this by @chjj  (and possibly others)! I've updated the patch to work with bitcoin core v0.10.2 and found similar things to what @chjj said above. Ive also made the patched bitcoind compile and link on a Mac with small changes to the Makefile.daemon.include file. When starting the net threads with AppInit2, the blockchain sync's, but the main process runs out of memory soon enough. I noticed it using over 3GB of memory, but I am not sure what memory levels it dumped out at. I think I can fiddle with the binding enough to shore this up. thanks @chjj for the work on this.
