### ISSUE TITLE
Compiling requires some additional modifications

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcoind.js#3]
A few additional steps are needed to compile the bindings.

- Copying `./libbitcoind/src/leveldb/helpers/memenv/memenv.h` to `/usr/local/include/`
- Compiling and installing `./libbitcoind/src/secp256k1/`
```bash
cd libbitcoind/src/secp256k1
./configure
make
install
```
- Adding additional libraries (though not ideal)
```js
'libraries': [
  ...
  '/usr/lib/libdb_cxx-4.8.so',
  '/usr/local/lib/libsecp256k1.a',
  '/usr/lib/x86_64-linux-gnu/libboost_program_options.so',
  '/usr/lib/x86_64-linux-gnu/libanl.so'
]
```

**Comment by chjj** [comment]
Yeah, that memenv.h nonsense was a pain. I should have mentioned it in the readme.
