### ISSUE TITLE
Primary Bindings for Transactions

### ISSUE THREAD

**Issue by braydonf** [bitpay/bitcoind.js#4]
The primary methods needed are:
- getInfo
- getRawTransaction
- sendRawTransaction
- getTransaction

Wallet functionality isn't needed, and `libbitcoind.so` could be compiled with the `--disable-wallet` flag.

**Comment by kleetus** [comment]
we've got getInfo done, we won't be doing getRawTx or sendRawTx right away. That just leaves getTx.

**Comment by braydonf** [comment]
This should be complete now with:
- getTransaction
- sendTransaction
- getInfo
