### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by mvayngrib** [bitpay/bitcoind.js#59]
i tried setting it up on my Mac but had some issues, and I don't want to make this a forum for debugging my build. Could you provide a Dockerfile? Thanks!

**Comment by braydonf** [comment]
We've moved the project over to [bitcore-node](https://github.com/bitpay/bitcore-node), and now distribute binaries, which should also help. I've copied this issue over to https://github.com/bitpay/bitcore-node/issues/122
